import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import QueryProvider from "@/components/providers/query-provider";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Up & Grinding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html
      lang="en" className={cn("font-sans", geist.variable)}
      
    >
      
      <body className={cn("min-h-full flex flex-col font-sans", geist.variable)}>
        <QueryProvider>
        {children}
        </QueryProvider>
      </body>
    </html>
  );
}
