import type { Metadata } from "next";
import "@/app/globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import Link from "next/link";
import Image from "next/image";
import QueryProvider from "@/components/providers/query-provider";
const geist = Geist({subsets:['latin'],variable:'--font-sans'});
import {Toaster} from "react-hot-toast";

export const metadata: Metadata = {
 title: "Up & Grinding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html
      lang="en" className={cn("font-sans", geist.variable)}
      
    >
      <body className="min-h-full flex flex-col">
        <header>
          <div className="py-5 px-10 flex items-center justify-between xl:pr-30">
            <Image src={'/logo.png'} alt="logo" width={200} height={200}/>
            <div className="flex gap-10 font-semibold text-foreground/90">
                <Link href={'/admin/dashboard'}>Dashboard</Link>
                <Link href={'/admin/products'}>Products</Link>
                <Link href={'/admin/orders'}>Orders</Link>
                <Link href={'/admin/customers'}>Customers</Link>
            </div>
            <Link href={'/login'}>Logout</Link>
          </div>
        </header>
        <QueryProvider>
        <Toaster/>
        {children}
        </QueryProvider>
      </body>
    </html>
  );
}
