import type { Metadata } from "next";
import "@/app/globals.css"
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import QueryProvider from "@/components/providers/query-provider";
import { Toaster } from "react-hot-toast";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Up & Grinding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html
      lang="en" className={cn("font-sans", geist.variable)}
      
    >
      
      <body className="min-h-full flex flex-col">
        <Header/>
        <QueryProvider>
        <Toaster/>
        {children}
        <Footer/>
        </QueryProvider>
      </body>
    </html>
  );
}
